### ISSUE TITLE
Crash during LoadLibrary in AndroidDemo

### ISSUE THREAD

**Issue by Larpoux** [williamwen1986/Luakit#5]
Hi William. 

I try to run AndroidDemo/NotificationTest/
I have a crash during startLuaKit during a LoadLibrary 👎 
(it works fine on iOS :-) )
[Note: If you want I can look to this myself]
``
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: luakit.com.notificationtest, PID: 11743
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/luakit.com.notificationtest-hwfAOvQ1y0ecBICVKMs7bQ==/base.apk", zip file "/data/app/luakit.com.notificationtest-hwfAOvQ1y0ecBICVKMs7bQ==/split_lib_dependencies_apk.apk", zip file "/data/app/luakit.com.notificationtest-hwfAOvQ1y0ecBICVKMs7bQ==/split_lib_resources_apk.apk", zip file "/data/app/luakit.com.notificationtest-hwfAOvQ1y0ecBICVKMs7bQ==/split_lib_slice_0_apk.apk", zip file "/data/app/luakit.com.notificationtest-hwfAOvQ1y0ecBICVKMs7bQ==/split_lib_slice_1_apk.apk", zip file "/data/app/luakit.com.notificationtest-hwfAOvQ1y0ecBICVKMs7bQ==/split_lib_slice_2_apk.apk", zip file "/data/app/luakit.com.notificationtest-hwfAOvQ1y0ecBICVKMs7bQ==/split_lib_slice_3_apk.apk", zip file "/data/app/luakit.com.notificationtest-hwfAOvQ1y0ecBICVKMs7bQ==/split_lib_slice_4_apk.apk", zip file "/data/app/luakit.com.notificationtest-hwfAOvQ1y0ecBICVKMs7bQ==/split_lib_slice_5_apk.apk", zip file "/data/app/luakit.com.notificationtest-hwfAOvQ1y0ecBICVKMs7bQ==/split_lib_slice_6_apk.apk", zip file "/data/app/luakit.com.notificationtest-hwfAOvQ1y0ecBICVKMs7bQ==/split_lib_slice_7_apk.apk", zip file "/data/app/luakit.com.notificationtest-hwfAOvQ1y0ecBICVKMs7bQ==/split_lib_slice_8_apk.apk", zip file "/data/app/luakit.com.notificationtest-hwfAOvQ1y0ecBICVKMs7bQ==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/luakit.com.notificationtest-hwfAOvQ1y0ecBICVKMs7bQ==/lib/x86, /system/lib]]] couldn't find "libluaFramework.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        at com.common.luakit.LuaHelper.<clinit>(LuaHelper.java:27)
        at com.common.luakit.LuaHelper.startLuaKit(Unknown Source:0)
        at luakit.com.notificationtest.MainActivity.onCreate(MainActivity.java:31)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/Process: Sending signal. PID: 11743 SIG: 9
Disconnected from the target VM, address: 'localhost:8617', transport: 'socket'
``

**Comment by Larpoux** [comment]
It is possibly tied with the fact that I cannot compile the AndroidFramework.
ERROR: Plugin with id 'com.android.library' not found.

I continue to investigate

**Comment by Larpoux** [comment]
To compile luakit on Android I had to modify build.gradle for lib_chromium and luakit and create a file settings.gradle
``
buildscript {
    repositories {
        jcenter()
        maven { url 'https://maven.google.com' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.1'
    }
}

allprojects {
    repositories {
        google() // and here
        jcenter()
    }
}

apply plugin: 'com.android.library'

android {
    compileSdkVersion 28



    defaultConfig {
        minSdkVersion 15
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    //implementation 'com.android.support:appcompat-v7:26.0.0-alpha1'
    //testImplementation 'junit:junit:4.12'
    //androidTestImplementation 'com.android.support.test:runner:0.5'
    //androidTestImplementation 'com.android.support.test.espresso:espresso-core:2.2.2'
    implementation project(':lib_chromium')
}
``

Setting.gradles:
``
include ':luakit', ':lib_chromium'
``

**Comment by Larpoux** [comment]
I had also to move lib_chromium under luakit directory, but probably because I am not good with gradle.

**Comment by williamwen1986** [comment]
I have not provide x86 so , try on real  android phone

**Comment by Larpoux** [comment]
Thank you William. I am working on gradle so that the builds will be ok (for me).
I will tell you when it will be done.
/larpoux

**Comment by Larpoux** [comment]
I am working on a complete rebuild of luakit framework for Android. Next version soon :-)
